package com.tmtai.management.book.dto;
// Generated Nov 7, 2018 10:52:52 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * BorrowBook generated by hbm2java
 */
public class BorrowBookEditDto{

    private Long id;
    private BookEditDto book;
    private UserEditDto user;
    private Date borrowDate;
    private Date payDate;
    private long number;

    public BorrowBookEditDto() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public BookEditDto getBook() {
        return this.book;
    }

    public void setBook(BookEditDto book) {
        this.book = book;
    }

    public UserEditDto getUser() {
        return this.user;
    }

    public void setUser(UserEditDto user) {
        this.user = user;
    }

    public Date getBorrowDate() {
        return this.borrowDate;
    }

    public void setBorrowDate(Date borrowDate) {
        this.borrowDate = borrowDate;
    }

    public Date getPayDate() {
        return this.payDate;
    }

    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    public long getNumber() {
        return this.number;
    }

    public void setNumber(long number) {
        this.number = number;
    }

}
