package com.tmtai.management.book.dto;
// Generated Nov 7, 2018 10:52:52 PM by Hibernate Tools 5.3.0.Beta2

import java.util.List;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

    private Integer id;
    private String code;
    private String link;
    private String icon;
    private boolean parent;
    private int position;
    private Integer parentId;
    private List<MenuDto> listSubMenu;

    public Menu() {
    }

    public Menu(String code, String link, String icon, boolean parent, int position) {
        this.code = code;
        this.link = link;
        this.icon = icon;
        this.parent = parent;
        this.position = position;
    }

    public Menu(String code, String link, String icon, boolean parent, int position, Integer parentId) {
        this.code = code;
        this.link = link;
        this.icon = icon;
        this.parent = parent;
        this.position = position;
        this.parentId = parentId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public boolean isParent() {
        return this.parent;
    }

    public void setParent(boolean parent) {
        this.parent = parent;
    }

    public int getPosition() {
        return this.position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public List<MenuDto> getListSubMenu() {
        return listSubMenu;
    }

    public void setListSubMenu(List<MenuDto> listSubMenu) {
        this.listSubMenu = listSubMenu;
    }

}
