package com.tmtai.management.book.dto;
// Generated Nov 7, 2018 10:52:52 PM by Hibernate Tools 5.3.0.Beta2

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * User generated by hbm2java
 */
public class UserSearchDto implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String username;
    private String password;
    private String firstName;
    private String lastName;
    private String address;
    private Date birthday;
    private String phone;
    private String identityCard;
    private String gender;
    private byte[] avatar;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private String deleteBy;
    private Date deleteDate;
    private List<String> roleForUsers = new ArrayList<>();
    private List<String> borrowBooks = new ArrayList<>();

    public UserSearchDto() {
    }

    public UserSearchDto(String username, String password, String firstName, String lastName, String address, Date birthday,
            String phone, String identityCard, String gender) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.birthday = birthday;
        this.phone = phone;
        this.identityCard = identityCard;
        this.gender = gender;
    }

    public UserSearchDto(String username, String password, String firstName, String lastName, String address, Date birthday,
            String phone, String identityCard, String gender, byte[] avatar, String createBy, Date createDate,
            String updateBy, Date updateDate, String deleteBy, Date deleteDate, List<String> roleForUsers,
            List<String> borrowBooks) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.birthday = birthday;
        this.phone = phone;
        this.identityCard = identityCard;
        this.gender = gender;
        this.avatar = avatar;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.deleteBy = deleteBy;
        this.deleteDate = deleteDate;
        this.roleForUsers = roleForUsers;
        this.borrowBooks = borrowBooks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIdentityCard() {
        return identityCard;
    }

    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public byte[] getAvatar() {
        return avatar;
    }

    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getDeleteBy() {
        return deleteBy;
    }

    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy;
    }

    public Date getDeleteDate() {
        return deleteDate;
    }

    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    public List<String> getRoleForUsers() {
        return roleForUsers;
    }

    public void setRoleForUsers(List<String> roleForUsers) {
        this.roleForUsers = roleForUsers;
    }

    public List<String> getBorrowBooks() {
        return borrowBooks;
    }

    public void setBorrowBooks(List<String> borrowBooks) {
        this.borrowBooks = borrowBooks;
    }

}
