package com.tmtai.management.book.dto;
// Generated Nov 7, 2018 10:52:52 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class UserDto implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String username;
    private String password;
    private String firstName;
    private String lastName;
    private String address;
    private Date birthday;
    private String phone;
    private String identityCard;
    private String gender;
    private byte[] avatar;
    private String createBy;
    private Date createDate;
    private String updateBy;
    private Date updateDate;
    private String deleteBy;
    private Date deleteDate;
    private Set roleForUsers = new HashSet(0);
    private Set borrowBooks = new HashSet(0);

    public UserDto() {
    }

    public UserDto(String username, String password, String firstName, String lastName, String address, Date birthday,
            String phone, String identityCard, String gender) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.birthday = birthday;
        this.phone = phone;
        this.identityCard = identityCard;
        this.gender = gender;
    }

    public UserDto(String username, String password, String firstName, String lastName, String address, Date birthday,
            String phone, String identityCard, String gender, byte[] avatar, String createBy, Date createDate,
            String updateBy, Date updateDate, String deleteBy, Date deleteDate, Set roleForUsers, Set borrowBooks) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.birthday = birthday;
        this.phone = phone;
        this.identityCard = identityCard;
        this.gender = gender;
        this.avatar = avatar;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
        this.deleteBy = deleteBy;
        this.deleteDate = deleteDate;
        this.roleForUsers = roleForUsers;
        this.borrowBooks = borrowBooks;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getIdentityCard() {
        return this.identityCard;
    }

    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public byte[] getAvatar() {
        return this.avatar;
    }

    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getDeleteBy() {
        return this.deleteBy;
    }

    public void setDeleteBy(String deleteBy) {
        this.deleteBy = deleteBy;
    }

    public Date getDeleteDate() {
        return this.deleteDate;
    }

    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    public Set getRoleForUsers() {
        return this.roleForUsers;
    }

    public void setRoleForUsers(Set roleForUsers) {
        this.roleForUsers = roleForUsers;
    }

    public Set getBorrowBooks() {
        return this.borrowBooks;
    }

    public void setBorrowBooks(Set borrowBooks) {
        this.borrowBooks = borrowBooks;
    }

}
